import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const montserrat = Montserrat({
    subsets: ["latin"],
    variable: "--font-montserrat",
});

export default function UserLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className={montserrat.variable}>
            <body className="antialiased">
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
